import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'formatters.dart';

class QuotePdfGenerator {
  // Brand Colors - Fern Green
  static final PdfColor primaryColor = PdfColor.fromHex('#2D5A3D'); 
  static final PdfColor lightBg = PdfColor.fromHex('#F0F4F1'); // Very faint green for box backgrounds
  static final PdfColor textDark = PdfColors.grey800;
  static final PdfColor textLight = PdfColors.grey600;

  static Future<Uint8List> generate(PdfPageFormat format, Map<String, dynamic> data) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format.copyWith(
          marginTop: 1.5 * PdfPageFormat.cm,
          marginBottom: 1.5 * PdfPageFormat.cm,
          marginLeft: 1.5 * PdfPageFormat.cm,
          marginRight: 1.5 * PdfPageFormat.cm,
        ),
        header: (context) => _buildHeader(data),
        footer: (context) => _buildFooter(context),
        build: (context) =>[
          _buildInfoSection(data),
          pw.SizedBox(height: 30),
          _buildItemsTable(data),
          pw.SizedBox(height: 20),
          _buildGrandTotal(data),
          pw.SizedBox(height: 50),
          _buildSignatures(data),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(Map<String, dynamic> data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children:[
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children:[
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children:[
                pw.Text('GREENTECH', style: pw.TextStyle(color: primaryColor, fontSize: 28, fontWeight: pw.FontWeight.bold)),
                pw.Text('HVAC Manufacturing & Solutions', style: pw.TextStyle(fontSize: 12, color: textDark)),
                pw.SizedBox(height: 4),
                pw.Text('Paranaque City, NCR, Philippines', style: pw.TextStyle(fontSize: 10, color: textLight)),
              ],
            ),
            pw.Container(
              padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              decoration: pw.BoxDecoration(
                color: lightBg, // Uses the exact light background
                borderRadius: pw.BorderRadius.circular(8),
                border: pw.Border.all(color: primaryColor, width: 1.5),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children:[
                  pw.Text('QUOTATION', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: primaryColor)),
                  pw.SizedBox(height: 6),
                  pw.Text('Ref: ${data['reference_no'] ?? 'N/A'}', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: textDark)),
                  pw.Text('Date: ${Formatters.parseDate(data['created_at'])}', style: pw.TextStyle(fontSize: 10, color: textLight)),
                ],
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 20),
        pw.Divider(color: primaryColor, thickness: 2),
        pw.SizedBox(height: 20),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Column(
      children:[
        pw.Divider(color: PdfColors.grey300),
        pw.SizedBox(height: 8),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children:[
            pw.Text('Generated by GreenTech Quote System', style: pw.TextStyle(fontSize: 9, color: textLight)),
            pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: pw.TextStyle(fontSize: 9, color: textLight)),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildInfoSection(Map<String, dynamic> data) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children:[
        // Prepared For (Client)
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children:[
              pw.Text('PREPARED FOR:', style: pw.TextStyle(fontSize: 10, color: textLight, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text(
                data['company_name'] ?? data['customer_name'] ?? 'Unknown Client',
                style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: textDark),
              ),
              if (Formatters.isNotEmpty(data['company_location']))
                pw.Text(data['company_location'], style: pw.TextStyle(fontSize: 11, color: textDark)),
              pw.SizedBox(height: 4),
              pw.Text('Attn: ${data['attention_name'] ?? 'Purchasing'}', style: pw.TextStyle(fontSize: 11, color: textDark)),
            ],
          ),
        ),
        pw.SizedBox(width: 20),
        // Project Details
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children:[
              pw.Text('PROJECT DETAILS:', style: pw.TextStyle(fontSize: 10, color: textLight, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text(
                data['customer_project'] ?? 'Unknown Project',
                style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: textDark),
                textAlign: pw.TextAlign.right,
              ),
              if (Formatters.isNotEmpty(data['project_location']))
                pw.Text(data['project_location'], style: pw.TextStyle(fontSize: 11, color: textDark), textAlign: pw.TextAlign.right),
              pw.SizedBox(height: 4),
              pw.Text('Agent: ${data['created_by_name'] ?? 'N/A'}', style: pw.TextStyle(fontSize: 11, color: textDark)),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildItemsTable(Map<String, dynamic> data) {
    final items = (data['items'] as List<dynamic>?) ??[];

    return pw.TableHelper.fromTextArray(
      border: null,
      headerStyle: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold, fontSize: 11),
      headerDecoration: pw.BoxDecoration(color: primaryColor),
      rowDecoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey200, width: 0.5)),
      ),
      oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey50),
      cellStyle: pw.TextStyle(fontSize: 10, color: textDark),
      headerHeight: 35,
      cellHeight: 35,
      cellPadding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.center,
        2: pw.Alignment.center,
        3: pw.Alignment.centerRight,
        4: pw.Alignment.centerRight,
      },
      columnWidths: {
        0: const pw.FlexColumnWidth(4),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(1),
        3: const pw.FlexColumnWidth(2),
        4: const pw.FlexColumnWidth(2.5), // Gave "Amount" column slightly more space
      },
      headers:['Description', 'Dimensions', 'Qty', 'Unit Price', 'Amount'],
      data: items.map<List<String>>((item) {
        final customizations = Formatters.formatCustomizations(item['customizations']);
        final desc = item['description'] ?? 'Unknown';
        final code = item['item_code'] ?? 'N/A';
        return [
          '$desc ($code)$customizations',
          '${item['length'] ?? 0} x ${item['width'] ?? 0}',
          item['qty']?.toString() ?? '0',
          'PHP ${Formatters.formatPrice(item['final_unit_price'])}',
          'PHP ${Formatters.formatPrice(item['line_total'])}',
        ];
      }).toList(),
    );
  }

  static pw.Widget _buildGrandTotal(Map<String, dynamic> data) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.end,
      children:[
        pw.Container(
          width: 300, // Increased width to prevent text squishing on massive numbers
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: lightBg, // Clean light background
            borderRadius: pw.BorderRadius.circular(8),
            border: pw.Border.all(color: primaryColor, width: 1.5),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children:[
              pw.Text('GRAND TOTAL', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: primaryColor)),
              pw.SizedBox(width: 8), // Ensures minimal spacing if the number is huge
              pw.Expanded(
                child: pw.Text(
                  'PHP ${Formatters.formatPrice(data['grand_total'])}', 
                  style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: primaryColor),
                  textAlign: pw.TextAlign.right,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildSignatures(Map<String, dynamic> data) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children:[
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children:[
            pw.Container(width: 180, height: 1, color: textDark),
            pw.SizedBox(height: 6),
            pw.Text('Prepared By', style: pw.TextStyle(fontSize: 9, color: textLight)),
            pw.Text(data['created_by_name'] ?? 'Sales Representative', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: textDark)),
          ],
        ),
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children:[
            pw.Container(width: 180, height: 1, color: textDark),
            pw.SizedBox(height: 6),
            pw.Text('Accepted By', style: pw.TextStyle(fontSize: 9, color: textLight)),
            pw.Text('Signature over printed name', style: pw.TextStyle(fontSize: 11, color: textDark)),
          ],
        ),
      ],
    );
  }
}
